# https://kodiakhq.com/docs/config-reference
version = 1

[merge]
automerge_label = "automerge"
require_automerge_label = true
blocking_labels = ["do-not-merge", "wip", "major"]
blocking_title_regex = "^(WIP|wip|Draft):"
method = "squash"
delete_branch_on_merge = true
notify_on_conflict = true
prioritize_ready_to_merge = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true

[update]
always = false
autoupdate_label = "autoupdate"
ignored_usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
