packages:
  - "apps/*"
  - "packages/*"
overrides:
  deepmerge-ts: ">=8.0.2"
  fast-uri@3: 3.1.6
  mysql2: 3.23.1
  qs: "6.16.0"
allowBuilds:
  esbuild: true
  prisma: true
  "@prisma/engines": true
  "@scarf/scarf": false
  unrs-resolver: false
  msgpackr-extract: false
  protobufjs: false
