packages:
  - "apps/*"
  - "packages/*"
overrides:
  deepmerge-ts: ">=8.0.2"
allowBuilds:
  esbuild: true
  prisma: true
  "@prisma/engines": true
  "@scarf/scarf": false
  unrs-resolver: false
  msgpackr-extract: false
