#!/usr/bin/env node
/**
 * Emits one TaxRule JSON per row in the phase 03-04 exemplar table.
 * Disjointness: unique (supplier, customer, supply_type, customer_is_business).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rulesDir = join(__dirname, "..", "rules");

/** @type {Array<{
 *   id: string;
 *   supplier: string;
 *   customer: string;
 *   supply_type: string;
 *   customer_is_business: boolean;
 *   rate: number;
 *   reverse: boolean;
 *   liability: "supplier" | "customer";
 *   legal_reference: string;
 *   invoice_text_block_id: string;
 *   place_of_supply: string;
 *   invoice_tax_shown: boolean;
 *   supplier_vat_registered: boolean;
 *   customer_vat_registered: boolean;
 * }>} */
const ROWS = [
  {
    id: "EU_DOMESTIC_B2B_SERVICE",
    supplier: "AT",
    customer: "AT",
    supply_type: "service",
    customer_is_business: true,
    rate: 20,
    reverse: false,
    liability: "supplier",
    legal_reference: "MS_A national VAT law (e.g. local UStG)",
    invoice_text_block_id: "EU_DOMESTIC_SERVICE_STANDARD",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_DOMESTIC_B2C_SERVICE",
    supplier: "AT",
    customer: "AT",
    supply_type: "service",
    customer_is_business: false,
    rate: 20,
    reverse: false,
    liability: "supplier",
    legal_reference: "MS_A national VAT law",
    invoice_text_block_id: "EU_DOMESTIC_SERVICE_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "EU_INTRACOMM_B2B_SERVICE",
    supplier: "AT",
    customer: "DE",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT Directive Art. 44, 196",
    invoice_text_block_id: "EU_RC_B2B_SERVICE",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_INTRACOMM_B2C_DIGITAL",
    supplier: "AT",
    customer: "DE",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 19,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU VAT rules for digital services to consumers",
    invoice_text_block_id: "EU_DIGITAL_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "EU_EXPORT_SERVICE_TO_THIRD",
    supplier: "AT",
    customer: "JP",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU VAT export rules, national law",
    invoice_text_block_id: "EU_EXPORT_SERVICE_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_EXPORT_GOODS_TO_THIRD",
    supplier: "AT",
    customer: "US",
    supply_type: "goods",
    customer_is_business: true,
    rate: 0,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU export and customs rules",
    invoice_text_block_id: "EU_EXPORT_GOODS_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_TO_EU_B2B_GOODS_INTRACOMM",
    supplier: "AT",
    customer: "DE",
    supply_type: "goods",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT intra-EU acquisition rules",
    invoice_text_block_id: "EU_RC_INTRACOMM_GOODS_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_TO_EU_B2C_GOODS_INTRACOMM",
    supplier: "AT",
    customer: "DE",
    supply_type: "goods",
    customer_is_business: false,
    rate: 19,
    reverse: false,
    liability: "supplier",
    legal_reference: "Distance selling / OSS rules",
    invoice_text_block_id: "EU_DISTANT_SELLING_GOODS_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "THIRD_TO_EU_B2B_SERVICE",
    supplier: "US",
    customer: "AT",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT Directive Art. 44, 196",
    invoice_text_block_id: "EU_RC_IMPORT_SERVICE_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: false,
    customer_vat_registered: true,
  },
  {
    id: "THIRD_TO_EU_B2C_DIGITAL",
    supplier: "US",
    customer: "AT",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 20,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU VAT digital services, Non-Union OSS",
    invoice_text_block_id: "EU_DIGITAL_IMPORT_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: false,
    customer_vat_registered: false,
  },
  {
    id: "US_TO_EU_B2B_SERVICE",
    supplier: "US",
    customer: "DE",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT Directive; US not VAT jurisdiction",
    invoice_text_block_id: "EU_RC_US_TO_EU_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: false,
    customer_vat_registered: true,
  },
  {
    id: "US_TO_EU_B2C_DIGITAL",
    supplier: "US",
    customer: "DE",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 19,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU digital services to consumers",
    invoice_text_block_id: "EU_DIGITAL_US_TO_EU_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: false,
    customer_vat_registered: false,
  },
  {
    id: "EU_TO_US_B2B_SERVICE",
    supplier: "AT",
    customer: "US",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: false,
    liability: "supplier",
    legal_reference: "US sales tax / nexus rules",
    invoice_text_block_id: "US_B2B_SERVICE_FROM_EU",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_TO_US_B2C_DIGITAL",
    supplier: "AT",
    customer: "US",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 0,
    reverse: false,
    liability: "supplier",
    legal_reference: "US digital tax rules (state-level)",
    invoice_text_block_id: "US_B2C_DIGITAL_FROM_EU",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "UAE_TO_EU_B2B_SERVICE",
    supplier: "AE",
    customer: "DE",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT Directive; UAE VAT export rules",
    invoice_text_block_id: "EU_RC_UAE_TO_EU_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "UAE_TO_EU_B2B_DIGITAL",
    supplier: "AE",
    customer: "DE",
    supply_type: "digital_service",
    customer_is_business: true,
    rate: 0,
    reverse: true,
    liability: "customer",
    legal_reference: "EU VAT Directive; UAE VAT on digital exports",
    invoice_text_block_id: "EU_RC_UAE_TO_EU_DIGITAL_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "UAE_TO_EU_B2C_DIGITAL",
    supplier: "AE",
    customer: "DE",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 19,
    reverse: false,
    liability: "supplier",
    legal_reference: "EU VAT rules; UAE VAT? (non-resident, export)",
    invoice_text_block_id: "EU_DIGITAL_UAE_TO_EU_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "EU_TO_UAE_B2B_SERVICE",
    supplier: "AT",
    customer: "AE",
    supply_type: "service",
    customer_is_business: true,
    rate: 5,
    reverse: true,
    liability: "customer",
    legal_reference: "UAE VAT Law on imported services (Reverse Charge)",
    invoice_text_block_id: "UAE_RC_IMPORT_SERVICE_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_TO_UAE_B2B_DIGITAL",
    supplier: "AT",
    customer: "AE",
    supply_type: "digital_service",
    customer_is_business: true,
    rate: 5,
    reverse: true,
    liability: "customer",
    legal_reference: "UAE VATP044, digital imported services",
    invoice_text_block_id: "UAE_RC_IMPORT_DIGITAL_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "EU_TO_UAE_B2C_DIGITAL",
    supplier: "AT",
    customer: "AE",
    supply_type: "digital_service",
    customer_is_business: false,
    rate: 5,
    reverse: false,
    liability: "supplier",
    legal_reference: "UAE VAT for non-resident digital suppliers",
    invoice_text_block_id: "UAE_DIGITAL_EU_TO_UAE_B2C",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: false,
  },
  {
    id: "DOMESTIC_SPECIAL_PROPERTY",
    supplier: "AT",
    customer: "AT",
    supply_type: "property",
    customer_is_business: true,
    rate: 20,
    reverse: false,
    liability: "supplier",
    legal_reference: "Special place-of-supply rules (property)",
    invoice_text_block_id: "EU_PROPERTY_SPECIAL",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "DOMESTIC_SPECIAL_EVENT",
    supplier: "AT",
    customer: "AT",
    supply_type: "special",
    customer_is_business: true,
    rate: 20,
    reverse: false,
    liability: "supplier",
    legal_reference: "Special rules for admission to events",
    invoice_text_block_id: "EU_EVENT_SPECIAL",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: true,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
  {
    id: "THIRD_TO_THIRD_B2B_SERVICE",
    supplier: "US",
    customer: "AE",
    supply_type: "service",
    customer_is_business: true,
    rate: 0,
    reverse: false,
    liability: "supplier",
    legal_reference: "Local VAT/GST rules of involved countries",
    invoice_text_block_id: "THIRD_TO_THIRD_GENERIC_B2B",
    place_of_supply: "{{customer_country}}",
    invoice_tax_shown: false,
    supplier_vat_registered: true,
    customer_vat_registered: true,
  },
];

function tupleKey(row) {
  return `${row.supplier}|${row.customer}|${row.supply_type}|${row.customer_is_business}`;
}

const seen = new Map();
for (const row of ROWS) {
  const key = tupleKey(row);
  if (seen.has(key)) {
    console.error(
      `Disjointness violation: ${row.id} collides with ${seen.get(key)} on ${key}`,
    );
    process.exit(1);
  }
  seen.set(key, row.id);
}

if (ROWS.length !== 23) {
  console.error(`Expected 23 rows, got ${ROWS.length}`);
  process.exit(1);
}

mkdirSync(rulesDir, { recursive: true });

for (const row of ROWS) {
  const rule = {
    rule_id: row.id,
    version: "1.0.0",
    description: `Matrix class ${row.id} (phase 03-04 exemplar)`,
    conditions: {
      supplier_country: row.supplier,
      customer_country: row.customer,
      supplier_is_business: true,
      customer_is_business: row.customer_is_business,
      supplier_vat_registered: row.supplier_vat_registered,
      customer_vat_registered: row.customer_vat_registered,
      supply_type: row.supply_type,
      channel: "direct",
    },
    effect: {
      place_of_supply_country: row.place_of_supply,
      tax_liability_party: row.liability,
      invoice_tax_rate: row.rate,
      invoice_tax_shown: row.invoice_tax_shown,
      reverse_charge_flag: row.reverse,
      legal_reference: row.legal_reference,
      invoice_text_block_id: row.invoice_text_block_id,
    },
    source_citation: [],
    tags: [row.supply_type],
  };

  const path = join(rulesDir, `${row.id}.json`);
  writeFileSync(path, `${JSON.stringify(rule, null, 2)}\n`);
}

console.log(`Wrote ${ROWS.length} rules to ${rulesDir}`);
